on:
  # schedule:
    # - cron: '0 * * * 1'
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

name: PR Verification
jobs:
  sonarQube:
    name: SonarQube Scan
    runs-on: linux
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build with Maven
      run: |
        cd initial
        mvn clean test jacoco:report
        ls -R
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: initial/**/jacoco.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/initial/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GH_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
